# Generated by Django 5.2.3 on 2025-07-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.IntegerField(),
        ),
    ]
