# Generated by Django 5.2.3 on 2025-07-02 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_ward2_ward3_ward4_ward5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ward2',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ward3',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ward4',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ward5',
            name='location',
        ),
    ]
