# Generated by Django 5.2.3 on 2025-07-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_remove_ward_location_remove_ward2_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('datetime', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ward2',
        ),
        migrations.DeleteModel(
            name='Ward3',
        ),
        migrations.DeleteModel(
            name='Ward4',
        ),
        migrations.DeleteModel(
            name='Ward5',
        ),
    ]
